name: CwFeedback
author: mario_fischer
category: Request
tags: [ajax, voting, rating, events, social]
demo: http://www.chipwreck.de/blog/software/cwfeedback/demo/
docs: http://www.chipwreck.de/blog/software/cwfeedback/help/

